### ISSUE TITLE
Canvas selection only works at certain angles with tillia pointer straight

### ISSUE THREAD

**Issue by Ituno** [studentutu/Tilia.UnityUI#6] opened 2023-01-30 12:39 UTC
From what i could tell from the way the selection seems to work right now, and granting that i did not mess up the setup, is that if the angle of the pointer is perpendicular or pointing up (so the origin is lower from the button) the button can be highlighted and pressed. Otherwise it does not. I also found out that if i pass the laser through the other hand (and it correctly stops on the hands collider) it somehow still raycasts through it and the angle problem dissapear. I don't know how to adress or what more info I should give but this is a wierd interaction I could not find a real solution to

**Comment by studentutu** [comment] 2023-01-30 13:08
that is a weird issue - it should use any angle  - as it solely relies on UIRaycasts (casting to UIElements)  - so no angles whatsoever.
Could you provide a sample project/scene where this issue is reproduced?  
It looks like you have something on the hands, a collider possibly, which interacts with UI raycasts. You can actually offset your UIRaycaster away from your hand collider so that it won't interact with it.

**Comment by blueflameknight** [comment] 2023-01-30 19:11
I will try and make the scene for you, the problem however happens not on your test level, we tried it on our, the same exact canvas made into a prefab and moved from your test level(on which it works) and on our level it just does not detect buttons below the half of the canvas if the pointer is inclined downwards(taller than the canvas). 
However thanks for the fast response, sorry for my slow one . I will get back to you with a smaller version of the project so you can take a look.

**Comment by blueflameknight** [comment] 2023-02-02 13:24
Hi, sorry for the late response, I am having a hard time sending you a "smaller version" of the project as i can't really seem to just export a level and all packages to a new project without breaking some references(sorry about my noobness) but i uploaded the full version for you to see and test : https://shillerisland.itch.io/vr-test   password: Studentutu
Try raising your hand and you may see what we mean. You can't click the buttons anymore

**Comment by studentutu** [comment] 2023-05-21 15:47
Still can't reproduce, but I have found another minor issue and also made a new [release ](https://github.com/studentutu/Tilia.UnityUI/releases/tag/3.0.2) ( please see breaking changes before updating)

**Comment by cooloo** [comment] 2023-06-28 06:32
I have the same problem.

**Comment by cooloo** [comment] 2023-06-28 06:37
![222](https://github.com/studentutu/Tilia.UnityUI/assets/11901841/254c0cff-afa6-46ed-a52d-e035c8ca6229)
![333](https://github.com/studentutu/Tilia.UnityUI/assets/11901841/b07918b7-c908-463c-8157-9bcb47021189)
Please check the image,I think the problem is the method "IsIntersectedByRay".

**Comment by studentutu** [comment] 2023-11-06 06:37
Good morning, I have tried all kinds variation - still can't reproduce on the test scene with default;t buttons. Can you make sure - you don't have anything overlapping those buttons?

**Comment by JamesSozoLabs** [comment] 2024-02-23 19:51
Good morning,
I have this same issue, but I narrowed down the issue to the VRTK4_3DGraphicRaycaster.
It's blocking mask is set to Default.

When I have a 3D object with a collider behind my UI then I am unable to click the button, but when I remove the 3D object or change its layer to something else, then the button works.

Am I mis understanding the VRTK4_3DGraphicRaycaster Blocking Mask?
I assume it's there to tell you which layers block your ray caster?
But in this case the UI is in front of the 3D object, so it shouldn't block the interaction.

Anyone else have this issue, or know what I'm doing wrong?

**Comment by studentutu** [comment] 2024-02-25 17:21
There might be a bug with the cast towards the UI if Collider is behind. Need to look into it

**Comment by JamesSozoLabs** [comment] 2024-02-28 07:59
Thanks @studentutu 
Please let me know if you find anything.

**Comment by studentutu** [comment] 2024-03-03 18:26
Working on the fix right now, updated Test scene and also reproduced.

**Comment by studentutu** [comment] 2024-03-03 20:03
Fixed in v3.0.3. It was caused by incorrect sorting at the end of the processing inside VRTK4_VRInputModule. Fixed it by using sorting from the default UI, but if event modules are different -> will use comparison only on the distance.

Thank you for contributing to the improvement of this package!
@cooloo @JamesSozoLabs @Ituno

**Closed by studentutu** 2024-03-03 20:03 UTC
